CC=gcc
CFLAGS=-Wall -o
ALL: main.c
	$(CC) $(CFLAGS) main main.c

.PHONY: clean

clean:
	rm *.o main /home/josh/C-DirectoryScan/aerospace-testing/OddBallFiles/* /home/josh/C-DirectoryScan/aerospace-testing/ProcessedFiles/*