CC=gcc
CFLAGS=-Wall -o
ALL: main.c
	$(CC) $(CFLAGS) main main.c

.PHONY: clean, cleanDir, cleanAll

clean:
	rm main

cleanDir:
	rm /home/josh/C-DirectoryScan/aerospace-testing/OddBallFiles/* /home/josh/C-DirectoryScan/aerospace-testing/ProcessedFiles/*

cleanAll:
	rm main /home/josh/C-DirectoryScan/aerospace-testing/OddBallFiles/* /home/josh/C-DirectoryScan/aerospace-testing/ProcessedFiles/*